# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'ChatGrow'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/chatgrow_thumbnail.svg'
- name: LOGO
  value: '/brand-assets/chatgrow_logo.svg'
- name: LOGO_DARK
  value: '/brand-assets/chatgrow_logo_dark.svg'
- name: BRAND_URL
  value: 'https://www.nexgrow.xyz'
- name: WIDGET_BRAND_URL
  value: 'https://www.nexgrow.xyz'
- name: BRAND_NAME
  value: 'ChatGrow'
- name: TERMS_URL
  value: 'https://www.chatwoot.com/terms-of-service'
- name: PRIVACY_URL
  value: 'https://www.chatwoot.com/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
